name: Sync with template

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Template Sync
        uses: AndreasAugustin/actions-template-sync@v2.5.2
        with:
          source_repo: "https://github.com/HugoBlox/theme-academic-cv.git"
          source_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
